### ISSUE TITLE
Extend Symmetrizer to support arbitrary integrals of motion

### ISSUE THREAD

**Issue by krivenko** [aeantipov/pomerol#10]
*Copied from https://github.com/krivenko/pomerol2triqs/issues/3*

Dear Igor,

At present, only Sz is used for state classification as in the default mode of pomerol. In the Slater Hamiltonian, for example, Lz (w/o SO) or Jz (w/ SO) could be additionally used to reduce the block size.

Is there any way to pass an Operator op to call symm.checkSymmetry(op)? Or, if not, which is the easiest way to extend the code?

It seems for me that one should extend the function pomerol_ed::diagonalize to be able to pass a list of operators that is used for additional symmetry check.

Best regards,
Junya

**Comment by krivenko** [comment]
@aeantipov 
So, what exactly has to be changed? Only `Symmetrizer::compute()`?
How much effort would it take?

**Comment by j-otsuki** [comment]
@krivenko 
Thank you for  your work, Igor.

Best,
Junya

**Comment by krivenko** [comment]
General integrals of motion make Pomerol crash.
Further investigation is required.

**Comment by aeantipov** [comment]
Igor, can you upload a failing test?

**Comment by krivenko** [comment]
I'm now preparing a test for pomerol2triqs (5 orbital atom, no bath) and it segfaults somewhere in `libpomerol.so`. I admit, this could be a problem of pomerol2triqs, so I need a bit of time to rule this possibility out.

**Comment by krivenko** [comment]
Okay, here is what I've been able to find so far.

* The crash is triggered by use of a non-abelian integral of motion, such as `S^2`. Those guys are more tricky than `N` or `S_z`, because they partition Hilbert space so that `c`/`c^+` are not necessarily one-to-one mappings between subspaces.

* Eigen reports a failed assertion in `HamiltonianPart::prepare()`.
```
/usr/include/eigen3/Eigen/src/Core/DenseCoeffsBase.h:337: Eigen::DenseCoeffsBase<Derived, 1>::Scalar& Eigen::DenseCoeffsBase<Derived, 1>::operator()(Eigen::DenseCoeffsBase<Derived, 1>::Index, Eigen::DenseCoeffsBase<Derived, 1>::Index) [with Derived = Eigen::Matrix<std::complex<double>, -1, -1, 1>; Eigen::DenseCoeffsBase<Derived, 1>::Scalar = std::complex<double>; Eigen::DenseCoeffsBase<Derived, 1>::Index = long int]: Assertion `row >= 0 && row < rows() && col >= 0 && col < cols()' failed.
```

This is from line 45 of `src/pomerol/HamiltonianPart.cpp`, I guess.

* It's very likely that we have a problem in `Operator::actRight()` and/or `StatesClassification::getInnerState()`.

**Comment by krivenko** [comment]
I can now see this being a conceptual problem, rather than a coding issue.

Here is the point: One cannot use non-abelian integrals of motion to partition the Hilbert space. In other words, an integral of motion Q can only be used if all initial basis states (Fock states) are its eigenstates.

Let's say `H` is our Hamiltonian, `Q` is an integral of motion we want to use for partitioning, and `|\psi_n>` is the orthonormal basis of Fock states. We characterize every basis state by an expectation value of `Q` computed in this state, `q_n = <\psi_n|Q|\psi_n>`.

By definition of integral of motion,

```
<\psi_1| [Q, H] |\psi_2> = <\psi_1| Q H |\psi_2> - <\psi_1| H Q |\psi_2> = 0.
```

In general we have `Q|\psi_n> = q_n |\psi_n> + |\tilde\psi_n>`, where `|\tilde\psi_n>` is orthogonal to `|\psi_n>`.

Let `|\psi_1>` and `|\psi_2>` be two different basis states with `q_1 != q_2`.

```
q_1 <\psi_1| H |\psi_2> - q_2 <\psi_1| H |\psi_2> +
<\tilde\psi_1| H |\psi_2> - <\psi_1| H |\tilde\psi_2> = 0
```

From this equation it follows that `<\psi_1| H |\psi_2> = 0` (Hamiltonian does not connect subspaces characterized by different quantum numbers), **only under an extra assumption `|\tilde\psi_1> = |\tilde\psi_2> = 0`**. And the assumption is equivalent to saying that `|\psi_1>`, `|\psi_2>` are eigenvectors of `Q`.

Now the question is how we detect the inappropriate integrals of motion in Pomerol?

**Comment by aeantipov** [comment]
Pomerol has a drawback of working in the Fock basis. Basically what we need to do is to rotate the basis, such as to have the eigenstates of operators as basis states.
So, Symmetrizer in that respect works correctly - it checks the commutation relation without resorting to a specific basis. It is in the next stage, called somewhat erroneously StateClassification (which is just a Fock state basis construction), that needs to define the Hamiltonian in a different basis.
On Friday, September 29, 2017 at 13:11 Igor Krivenko <notifications@github.com> wrote:

I can now see this being a conceptual problem, rather than a coding issue.

Here is the point: One cannot use non-abelian integrals of motion to partition the Hilbert space. In other words, an integral of motion Q can only be used if all initial basis states (Fock states) are its eigenstates.

Let's say H is our Hamiltonian, Q is an integral of motion we want to use for partitioning, and |\psi_n> is the orthonormal basis of Fock states. We characterize every basis state by an expectation value of Q computed in this state, q_n = <\psi_n|Q|\psi_n>.

By definition of integral of motion,

<\psi_1| [Q, H] |\psi_2> = <\psi_1| Q H |\psi_2> - <\psi_1| H Q |\psi_2> = 0. 

In general we have Q|\psi_n> = q_n |\psi_n> + |\tilde\psi_n>, where |\tilde\psi_n> is orthogonal to |\psi_n>.

Let |\psi_1> and |\psi_2> be two different basis states with q_1 != q_2.

q_1 <\psi_1| H |\psi_2> - q_2 <\psi_1| H |\psi_2> + <\tilde\psi_1| H |\psi_2> - <\psi_1| H |\tilde\psi_2> = 0 

From this equation it follows that <\psi_1| H |\psi_2> = 0 (Hamiltonian does not connect subspaces characterized by different quantum numbers), only under an extra assumption |\tilde\psi_1> = |\tilde\psi_2> = 0. And the assumption is equivalent to saying that |\psi_1>, |\psi_2> are eigenvectors of Q.

Now the question is how we detect the inappropriate integrals of motion in Pomerol?

**Comment by krivenko** [comment]
> Basically what we need to do is to rotate the basis, such as to have the eigenstates of operators as basis states. 

Rotation of the basis makes a little sense, as we would effectively need to diagonalize two operators, the Hamiltonian, and the integral of motion in question. And, in fact, even more if we have multiple integrals of motion.

I'd say `checkSymmetry()` should simply ignore IOM operators that don't commute with all occupation number operators.

**Comment by aeantipov** [comment]
To be reopened if we have any idea how to do better.
